Unstoppable: 
	forge test --match-test testExploit --match-contract Unstoppable

NaiveReceiver:
	forge test --match-test testExploit --match-contract NaiveReceiver -vvvv

Truster:
	forge test --match-test testExploit --match-contract Truster -vvvv
	
SideEntrance:
	forge test --match-test testExploit --match-contract SideEntrance -vvvv
	
TheRewarder:
	forge test --match-test testExploit --match-contract TheRewarder -vv

Selfie:
	forge test --match-test testExploit --match-contract Selfie -vvvv

Compromised:
	forge test --match-test testExploit --match-contract Compromised

Puppet:
	forge test --match-test testExploit --match-contract Puppet -vv

PuppetV2:
	forge test --match-test testExploit --match-contract PuppetV2

FreeRider:
	forge test --match-test testExploit --match-contract FreeRider -vv

Backdoor:
	forge test --match-test testExploit --match-contract Backdoor -vvv

Climber:
	forge test --match-test testExploit --match-contract Climber -vvv

JuniorMiners:
	forge test --match-test testExploit --match-contract JuniorMiners

